---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ops.db.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.db.io
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - ops.db.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ops.db.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.db.io
  resources:
  - restores/finalizers
  verbs:
  - update
- apiGroups:
  - ops.db.io
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ops.db.io
  resources:
  - stats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.db.io
  resources:
  - stats/finalizers
  verbs:
  - update
- apiGroups:
  - ops.db.io
  resources:
  - stats/status
  verbs:
  - get
  - patch
  - update
