# permissions for end users to view stats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stats-viewer-role
rules:
- apiGroups:
  - ops.db.io
  resources:
  - stats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.db.io
  resources:
  - stats/status
  verbs:
  - get
