# permissions for end users to edit stats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stats-editor-role
rules:
- apiGroups:
  - ops.db.io
  resources:
  - stats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.db.io
  resources:
  - stats/status
  verbs:
  - get
